schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "file_localizer"
version = "1.0.0"
name = "Localize texture images"
tagline = "Copies all image texture files to a local dir"
maintainer = "Renzo Gerritzen"
# Supported types: "add-on", "theme"
type = "add-on"

blender_version_min = "3.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]